# @name get-prompts
GET http://localhost:3333/prompts

###

# @name uploads
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----Boundary

----Boundary
Content-Disposition: form-data; name="file"; filename="Alarm01.mp3"
Content-Type: audio/mpeg

./Alarm01.mp3
----Boundary--

###

# @name transcription
POST http://localhost:3333/videos/1/transcription
Content-Type: "application/json"

{
    "prompt": ""
}

###

# @name generate
POST http://localhost:3333/ai/complete
Content-Type: "application/json"

{
    "videoId": "",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}